# Generated by Django 4.2.3 on 2026-07-21 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LieuService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lieu_services', to='tickets.lieu')),
            ],
            options={
                'ordering': ['lieu__name', 'service__name'],
            },
        ),
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('NETWORK_TELECOM_HELPDESK', 'Network / Telecom / Helpdesk'), ('APPLICATION_DATABASE_SOFTWARE', 'Application / Database / Software')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_problem_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('NETWORK_TELECOM_HELPDESK', 'Network / Telecom / Helpdesk'), ('APPLICATION_DATABASE_SOFTWARE', 'Application / Database / Software')], max_length=40)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='CREATED', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_validation_decision', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REFUSED', 'Refused')], max_length=20, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_assigned_by_me', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('problem_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.problemtype')),
                ('requester_lieu_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tickets', to='tickets.lieuservice')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL)),
                ('responsible_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_tickets', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lieu_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='tickets.lieuservice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_ROUTED', 'Ticket routed'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_REASSIGNED', 'Ticket reassigned'), ('TICKET_RESOLVED', 'Ticket resolved'), ('RESOLUTION_ACCEPTED', 'Resolution accepted'), ('RESOLUTION_REFUSED', 'Resolution refused'), ('TICKET_CLOSED', 'Ticket closed'), ('COMMENT_ADDED', 'Comment added')], max_length=30)),
                ('old_status', models.CharField(blank=True, choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_history_actions', to=settings.AUTH_USER_MODEL)),
                ('new_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_ticket_assignments', to=settings.AUTH_USER_MODEL)),
                ('old_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_ticket_assignments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket')),
            ],
            options={
                'verbose_name_plural': 'Ticket histories',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='lieuservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lieu_services', to='tickets.service'),
        ),
        migrations.AlterUniqueTogether(
            name='lieuservice',
            unique_together={('lieu', 'service')},
        ),
    ]
