# Generated by Django 4.2.3 on 2026-07-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_ROUTED', 'Ticket routed'), ('TICKET_UPDATED', 'Ticket updated'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_REASSIGNED', 'Ticket reassigned'), ('TICKET_RESOLVED', 'Ticket resolved'), ('RESOLUTION_ACCEPTED', 'Resolution accepted'), ('RESOLUTION_REFUSED', 'Resolution refused'), ('TICKET_CLOSED', 'Ticket closed'), ('TICKET_CANCELLED', 'Ticket cancelled'), ('COMMENT_ADDED', 'Comment added')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='new_status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], max_length=20, null=True),
        ),
    ]
