# Generated by Django 4.2.3 on 2026-07-28 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_alter_ticket_status_alter_tickethistory_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_ROUTED', 'Ticket routed'), ('TICKET_UPDATED', 'Ticket updated'), ('TICKET_ASSIGNED', 'Ticket assigned'), ('TICKET_REASSIGNED', 'Ticket reassigned'), ('TICKET_RESOLVED', 'Ticket resolved'), ('RESOLUTION_ACCEPTED', 'Resolution accepted'), ('RESOLUTION_REFUSED', 'Resolution refused'), ('TICKET_CLOSED', 'Ticket closed'), ('TICKET_CANCELLED', 'Ticket cancelled'), ('COMMENT_ADDED', 'Comment added'), ('OPERATOR_RETURNED', 'Operator returned')], max_length=30),
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
